server:
  port: 8084

spring:
  application:
    name: library

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:library}
    username: "${DB_USER:postgres}"  # Usa 'postgres' por defecto si DB_USER no está definido
    password: "${DB_PASS:postgres}"  # Usa 'postgres' por defecto si DB_PASS no está definido
  sql:
    init:
      mode: always
    flyway:
      enabled: false


entries:
  reactive-web:
    base-url: "${BASE_PATH:/product/api/v1}"
    author:
      create: "/author/create"
      update: "/author/update/{id}"
      search: "/author/search"
      all-authors: "/author/all"
      detail: "/author/detail"
    user:
      login: "/auth/userlogin"
      register: "/register/user"
    book:
      create: "/book/create"
      search: "/book/search"
      detail: "/book/detail"
    loan:
      create: "/book/rent"

jwt:
  secret: ${JWT_SECRET:MQOv69j_r8UH484-UZMr-8j7F0OskMBFESurTrg0hDM}
  expiration: ${JWT_EXPIRATION:3600000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: "/swagger-ui.html"
    operations-sorter: alpha
    disable-swagger-default-url: true
    try-it-out-enabled: true
  show-actuator: true

